[build]
  # Especificamos el directorio donde se encuentra el código que se va a desplegar
  publish = "client"
  
  


[[redirects]]
  # Redirección para asegurar que Netlify sirva archivos correctamente
  from = "/*"
  to = "/index.html"
  status = 200

  [[headers]]
  for = "/script/*"
  [headers.values]
    Content-Type = "application/javascript"