[build]
functions = "functions"

[functions]
directory = "/.netlify/functions"

[[plugins]]
package = "@netlify/plugin-functions-install-core"


[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force=true